host: ""
port: 8317

tls:
  enable: false

remote-management:
  allow-remote: true
  secret-key: "5_g4GDbDl76ow2GiUjwstMK15ux0yRRbpzMXuD-vfrg"
  disable-control-panel: false

auth-dir: "/root/.cli-proxy-api"

api-keys:
  - "IBmlwvqNi8qX5IrRWlIPoHCHnQK21xLdCgdzQAxsuKw"

debug: false
commercial-mode: false
logging-to-file: false
usage-statistics-enabled: true

request-retry: 3
max-retry-interval: 30

quota-exceeded:
  switch-project: true
  switch-preview-model: true

routing:
  strategy: "round-robin"

nonstream-keepalive-interval: 0
